name: Setup repo and pnpm
description: Gets pnpm and runs commands necessary before executing other steps
runs:
  using: composite
  steps:
    # https://pnpm.io/continuous-integration
    - name: Install package manager
      uses: pnpm/action-setup@v3
      with:
        version: 8.15.4
        run_install: false
    - name: Set up Node.js w/ version from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
