name: Setup repo and pnpm
description: Gets pnpm and runs commands necessary before executing other steps
runs:
  using: composite
  steps:
    # https://pnpm.io/continuous-integration
    - name: Install package manager
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6
    - name: Set up Node.js w/ version from .nvmrc
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
