name: Setup repo and pnpm
description: Gets pnpm and runs commands necessary before executing other steps
runs:
  using: composite
  steps:
    # https://pnpm.io/continuous-integration
    - name: Install package manager
      uses: pnpm/action-setup@91ab88e2619ed1f46221f0ba42d1492c02baf788 # v6
    - name: Set up Node.js w/ version from .nvmrc
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
