name: Setup repo and pnpm
description: Gets pnpm and runs commands necessary before executing other steps
runs:
  using: composite
  steps:
    # https://pnpm.io/continuous-integration
    - name: Install package manager
      uses: pnpm/action-setup@v3
      with:
        version: 8.15.4
    - name: Set up Node.js w/ version from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org'
        cache: 'pnpm'
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
