/* eslint-disable */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get multiple playlists
         * @description Get user playlists
         */
        get: operations["getPlaylistsByIds"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get single playlist
         * @description Get playlist by id
         */
        get: operations["getPlaylist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{id}/relationships/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relationship: owner
         * @description Get playlist owner
         */
        get: operations["getPlaylistOwnersRelationship"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/{id}/relationships/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relationship: items
         * @description Get playlist items
         */
        get: operations["getPlaylistItemsRelationship"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playlists/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user's playlists
         * @description Get my playlists
         */
        get: operations["getPlaylistCollection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error_Document: {
            /** @description array of error objects */
            errors?: components["schemas"]["Error_Object"][];
            links?: components["schemas"]["Links"];
        };
        Error_Object: {
            /** @description unique identifier for this particular occurrence of the problem */
            id?: string;
            /** @description HTTP status code applicable to this problem */
            status?: string;
            /** @description application-specific error code */
            code?: string;
            /** @description human-readable explanation specific to this occurrence of the problem */
            detail?: string;
            source?: components["schemas"]["Error_Object_Source"];
        };
        /** @description object containing references to the primary source of the error */
        Error_Object_Source: {
            /**
             * @description a JSON Pointer [RFC6901] to the value in the request document that caused the error
             * @example /data/attributes/title
             */
            pointer?: string;
            /**
             * @description string indicating which URI query parameter caused the error.
             * @example countryCode
             */
            parameter?: string;
            /**
             * @description string indicating the name of a single request header which caused the error
             * @example X-some-custom-header
             */
            header?: string;
        };
        /** @description links object */
        Links: {
            /**
             * @description the link that generated the current response document
             * @example /artists/xyz/relationships/tracks
             */
            self: string;
            /**
             * @description the next page of data (pagination)
             * @example /artists/xyz/relationships/tracks?page[cursor]=zyx
             */
            next?: string;
        };
        External_Link: {
            /**
             * @description link to something that is related to a resource
             * @example https://tidal.com/browse/artist/1566
             */
            href: string;
            meta: components["schemas"]["External_Link_Meta"];
        };
        /** @description metadata about an external link */
        External_Link_Meta: {
            /**
             * @description external link type
             * @example TIDAL_SHARING
             * @enum {string}
             */
            type: "TIDAL_SHARING" | "TIDAL_AUTOPLAY_ANDROID" | "TIDAL_AUTOPLAY_IOS" | "TIDAL_AUTOPLAY_WEB" | "TWITTER" | "FACEBOOK" | "INSTAGRAM" | "TIKTOK" | "SNAPCHAT" | "HOMEPAGE";
        };
        Image_Link: {
            /**
             * @description link to an image
             * @example https://resources.tidal.com/images/717dfdae/beb0/4aea/a553/a70064c30386/80x80.jpg
             */
            href: string;
            meta: components["schemas"]["Image_Link_Meta"];
        };
        /** @description metadata about an image */
        Image_Link_Meta: {
            /**
             * Format: int32
             * @description image width (in pixels)
             * @example 80
             */
            width: number;
            /**
             * Format: int32
             * @description image height (in pixels)
             * @example 80
             */
            height: number;
        };
        /** @description Video providers relationship */
        Multi_Data_Relationship_Doc: {
            /** @description array of relationship resource linkages */
            data?: components["schemas"]["Resource_Identifier"][];
            links?: components["schemas"]["Links"];
        };
        /** @description attributes object representing some of the resource's data */
        Playlist_Attributes: {
            /**
             * @description Playlist name
             * @example My Playlist
             */
            name: string;
            /**
             * @description Playlist description
             * @example All the good details about what is inside this playlist
             */
            description?: string;
            /**
             * @description Indicates if the playlist has a duration and set number of tracks
             * @example true
             */
            bounded: boolean;
            /**
             * @description Duration of the playlist expressed in accordance with ISO 8601
             * @example P30M5S
             */
            duration?: string;
            /**
             * Format: int32
             * @description Number of items in the playlist
             * @example 5
             */
            numberOfItems?: number;
            /**
             * @description Sharing links to the playlist
             * @example true
             */
            externalLinks: components["schemas"]["Playlist_External_Link"][];
            /**
             * Format: date-time
             * @description Datetime of playlist creation (ISO 8601)
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Datetime of last modification of the playlist (ISO 8601)
             */
            lastModifiedAt: string;
            /**
             * @description Privacy setting of the playlist
             * @example PUBLIC
             */
            privacy: string;
            /**
             * @description The type of the playlist
             * @example EDITORIAL
             */
            playlistType: string;
            /**
             * @description Images associated with the playlist
             * @example true
             */
            imageLinks: components["schemas"]["Image_Link"][];
        };
        Playlist_Data_Document: {
            /** @description array of primary resource data */
            data?: components["schemas"]["Playlist_Resource"][];
            links?: components["schemas"]["Links"];
            included?: (components["schemas"]["Track_Resource"] | components["schemas"]["Video_Resource"] | components["schemas"]["User_Resource"])[];
        };
        /**
         * @description Sharing links to the playlist
         * @example true
         */
        Playlist_External_Link: {
            /**
             * @description link to something that is related to a resource
             * @example https://tidal.com/browse/artist/1566
             */
            href: string;
            meta: components["schemas"]["External_Link_Meta"];
        };
        /** @description relationships object describing relationships between the resource and other resources */
        Playlist_Relationships: {
            items: components["schemas"]["Multi_Data_Relationship_Doc"];
            owners: components["schemas"]["Multi_Data_Relationship_Doc"];
        };
        /** @description array of primary resource data */
        Playlist_Resource: {
            attributes?: components["schemas"]["Playlist_Attributes"];
            relationships?: components["schemas"]["Playlist_Relationships"];
            links?: components["schemas"]["Links"];
            /**
             * @description resource unique identifier
             * @example 12345
             */
            id: string;
            /**
             * @description resource unique type
             * @example tracks
             */
            type: string;
        };
        /** @description relationship resource linkage */
        Resource_Identifier: {
            /**
             * @description resource unique identifier
             * @example 12345
             */
            id: string;
            /**
             * @description resource unique type
             * @example tracks
             */
            type: string;
        };
        /** @description User entitlements */
        Singleton_Data_Relationship_Doc: {
            data?: components["schemas"]["Resource_Identifier"];
            links?: components["schemas"]["Links"];
        };
        /** @description attributes object representing some of the resource's data */
        Track_Attributes: {
            /**
             * @description Album item's title
             * @example Kill Jay Z
             */
            title: string;
            /**
             * @description Version of the album's item; complements title
             * @example Kill Jay Z
             */
            version?: string;
            /**
             * @description ISRC code
             * @example TIDAL2274
             */
            isrc: string;
            /**
             * @description Duration expressed in accordance with ISO 8601
             * @example P30M5S
             */
            duration: string;
            /**
             * @description Copyright information
             * @example (p)(c) 2017 S. CARTER ENTERPRISES, LLC. MARKETED BY ROC NATION & DISTRIBUTED BY ROC NATION/UMG RECORDINGS INC.
             */
            copyright?: string;
            /**
             * @description Indicates whether a catalog item consist of any explicit content
             * @example false
             */
            explicit: boolean;
            /**
             * Format: double
             * @description Track or video popularity (ranged in 0.00 ... 1.00). Conditionally visible
             * @example 0.56
             */
            popularity: number;
            /** @description Defines a catalog item availability e.g. for streaming, DJs, stems */
            availability?: ("STREAM" | "DJ" | "STEM")[];
            mediaTags: string[];
            /** @description Represents available links to something that is related to a catalog item, but external to the TIDAL API */
            externalLinks?: components["schemas"]["External_Link"][];
        };
        /** @description relationships object describing relationships between the resource and other resources */
        Track_Relationships: {
            albums: components["schemas"]["Multi_Data_Relationship_Doc"];
            artists: components["schemas"]["Multi_Data_Relationship_Doc"];
            providers: components["schemas"]["Multi_Data_Relationship_Doc"];
            similarTracks: components["schemas"]["Multi_Data_Relationship_Doc"];
            radio: components["schemas"]["Multi_Data_Relationship_Doc"];
        };
        Track_Resource: {
            attributes?: components["schemas"]["Track_Attributes"];
            relationships?: components["schemas"]["Track_Relationships"];
            links?: components["schemas"]["Links"];
            /**
             * @description resource unique identifier
             * @example 12345
             */
            id: string;
            /**
             * @description resource unique type
             * @example tracks
             */
            type: string;
        };
        /** @description attributes object representing some of the resource's data */
        User_Attributes: {
            /**
             * @description user name
             * @example username
             */
            username: string;
            /**
             * @description ISO 3166-1 alpha-2 country code
             * @example US
             */
            country: string;
            /**
             * @description email address
             * @example test@test.com
             */
            email?: string;
            /**
             * @description Is the email verified
             * @example true
             */
            emailVerified?: boolean;
            /**
             * @description Users first name
             * @example John
             */
            firstName?: string;
            /**
             * @description Users last name
             * @example Rambo
             */
            lastName?: string;
        };
        /** @description relationships object describing relationships between the resource and other resources */
        User_Relationships: {
            entitlements: components["schemas"]["Singleton_Data_Relationship_Doc"];
        };
        User_Resource: {
            attributes?: components["schemas"]["User_Attributes"];
            relationships?: components["schemas"]["User_Relationships"];
            links?: components["schemas"]["Links"];
            /**
             * @description resource unique identifier
             * @example 12345
             */
            id: string;
            /**
             * @description resource unique type
             * @example tracks
             */
            type: string;
        };
        /** @description attributes object representing some of the resource's data */
        Video_Attributes: {
            /**
             * @description Album item's title
             * @example Kill Jay Z
             */
            title: string;
            /**
             * @description Version of the album's item; complements title
             * @example Kill Jay Z
             */
            version?: string;
            /**
             * @description ISRC code
             * @example TIDAL2274
             */
            isrc: string;
            /**
             * @description Duration expressed in accordance with ISO 8601
             * @example P30M5S
             */
            duration: string;
            /**
             * @description Copyright information
             * @example (p)(c) 2017 S. CARTER ENTERPRISES, LLC. MARKETED BY ROC NATION & DISTRIBUTED BY ROC NATION/UMG RECORDINGS INC.
             */
            copyright?: string;
            /**
             * Format: date
             * @description Release date (ISO-8601)
             * @example 2017-06-27
             */
            releaseDate?: string;
            /**
             * @description Indicates whether a catalog item consist of any explicit content
             * @example false
             */
            explicit: boolean;
            /**
             * Format: double
             * @description Track or video popularity (ranged in 0.00 ... 1.00). Conditionally visible
             * @example 0.56
             */
            popularity: number;
            /** @description Defines a catalog item availability e.g. for streaming, DJs, stems */
            availability?: ("STREAM" | "DJ" | "STEM")[];
            /** @description Represents available links to, and metadata about, an album item images */
            imageLinks?: components["schemas"]["Image_Link"][];
            /** @description Represents available links to something that is related to a catalog item, but external to the TIDAL API */
            externalLinks?: components["schemas"]["External_Link"][];
        };
        /** @description relationships object describing relationships between the resource and other resources */
        Video_Relationships: {
            albums: components["schemas"]["Multi_Data_Relationship_Doc"];
            artists: components["schemas"]["Multi_Data_Relationship_Doc"];
            providers: components["schemas"]["Multi_Data_Relationship_Doc"];
        };
        Video_Resource: {
            attributes?: components["schemas"]["Video_Attributes"];
            relationships?: components["schemas"]["Video_Relationships"];
            links?: components["schemas"]["Links"];
            /**
             * @description resource unique identifier
             * @example 12345
             */
            id: string;
            /**
             * @description resource unique type
             * @example tracks
             */
            type: string;
        };
        /** @description attributes object representing some of the resource's data */
        Artist_Attributes: {
            /**
             * @description Artist name
             * @example JAY Z
             */
            name: string;
            /**
             * Format: double
             * @description Artist popularity (ranged in 0.00 ... 1.00). Conditionally visible
             * @example 0.56
             */
            popularity: number;
            /** @description Represents available links to, and metadata about, an artist images */
            imageLinks?: components["schemas"]["Image_Link"][];
            /** @description Represents available links to something that is related to an artist resource, but external to the TIDAL API */
            externalLinks?: components["schemas"]["External_Link"][];
        };
        /** @description relationships object describing relationships between the resource and other resources */
        Artist_Relationships: {
            albums: components["schemas"]["Multi_Data_Relationship_Doc"];
            tracks: components["schemas"]["Multi_Data_Relationship_Doc"];
            videos: components["schemas"]["Multi_Data_Relationship_Doc"];
            similarArtists: components["schemas"]["Multi_Data_Relationship_Doc"];
            trackProviders: components["schemas"]["Artist_Track_Providers_Relationship"];
            radio: components["schemas"]["Multi_Data_Relationship_Doc"];
        };
        Artist_Resource: {
            attributes?: components["schemas"]["Artist_Attributes"];
            relationships?: components["schemas"]["Artist_Relationships"];
            links?: components["schemas"]["Links"];
            /**
             * @description resource unique identifier
             * @example 12345
             */
            id: string;
            /**
             * @description resource unique type
             * @example tracks
             */
            type: string;
        };
        /** @description Providers that have released tracks for this artist */
        Artist_Track_Providers_Relationship: {
            data?: components["schemas"]["Artist_Track_Providers_Resource_Identifier"][][];
            links?: components["schemas"]["Links"];
        };
        Artist_Track_Providers_Resource_Identifier: {
            /**
             * @description resource unique identifier
             * @example 12345
             */
            id: string;
            /**
             * @description resource unique type
             * @example tracks
             */
            type: string;
            meta?: components["schemas"]["Artist_Track_Providers_Resource_Identifier_Meta"];
        };
        Artist_Track_Providers_Resource_Identifier_Meta: {
            /**
             * Format: int64
             * @description total number of tracks released together with the provider
             * @example 14
             */
            numberOfTracks: number;
        };
        Playlist_Owners_Relationship_Document: {
            /** @description array of relationship resource linkages */
            data?: components["schemas"]["Resource_Identifier"][];
            links?: components["schemas"]["Links"];
            included?: (components["schemas"]["User_Resource"] | components["schemas"]["Artist_Resource"])[];
        };
        Playlist_Items_Relationship_Document: {
            /** @description array of relationship resource linkages */
            data?: components["schemas"]["Resource_Identifier"][];
            links?: components["schemas"]["Links"];
            included?: (components["schemas"]["Track_Resource"] | components["schemas"]["Video_Resource"])[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPlaylistsByIds: {
        parameters: {
            query: {
                /**
                 * @description Country code (ISO 3166-1 alpha-2)
                 * @example US
                 */
                countryCode: string;
                /**
                 * @description Allows the client to customize which related resources should be returned. Available options: items, owners
                 * @example items
                 */
                include?: ("items" | "owners")[];
                /**
                 * @description public.usercontent.getPlaylists.ids.descr
                 * @example 123456
                 */
                "filter[id]"?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlists retrieved successfully */
            200: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Playlist_Data_Document"];
                };
            };
            /** @description Bad request on client party. Ensure the proper HTTP request is sent (query parameters, request body, etc.). */
            400: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Resource not found. The requested resource is not found. */
            404: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Method not supported. Ensure a proper HTTP method for an HTTP request is used. */
            405: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Not acceptable. The server doesn't support any of the requested by client acceptable content types. */
            406: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Unsupported Media Type. The API is using content negotiation. Ensure the proper media type is set into Content-Type header. */
            415: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Internal Server Error. Something went wrong on the server party. */
            500: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
        };
    };
    getPlaylist: {
        parameters: {
            query: {
                /**
                 * @description Country code (ISO 3166-1 alpha-2)
                 * @example US
                 */
                countryCode: string;
                /**
                 * @description Allows the client to customize which related resources should be returned. Available options: items, owners
                 * @example items
                 */
                include?: ("items" | "owners")[];
            };
            header?: never;
            path: {
                /**
                 * @description TIDAL playlist id
                 * @example 12345678
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlist retrieved successfully */
            200: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Playlist_Data_Document"];
                };
            };
            /** @description Bad request on client party. Ensure the proper HTTP request is sent (query parameters, request body, etc.). */
            400: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Resource not found. The requested resource is not found. */
            404: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Method not supported. Ensure a proper HTTP method for an HTTP request is used. */
            405: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Not acceptable. The server doesn't support any of the requested by client acceptable content types. */
            406: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Unsupported Media Type. The API is using content negotiation. Ensure the proper media type is set into Content-Type header. */
            415: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Internal Server Error. Something went wrong on the server party. */
            500: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
        };
    };
    getPlaylistOwnersRelationship: {
        parameters: {
            query: {
                /**
                 * @description Country code (ISO 3166-1 alpha-2)
                 * @example US
                 */
                countryCode: string;
                /**
                 * @description Allows the client to customize which related resources should be returned. Available options: owners
                 * @example owners
                 */
                include?: "owners"[];
            };
            header?: never;
            path: {
                /**
                 * @description TIDAL playlist id
                 * @example 12345678
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlist owner retrieved successfully */
            200: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Playlist_Owners_Relationship_Document"];
                };
            };
            /** @description Bad request on client party. Ensure the proper HTTP request is sent (query parameters, request body, etc.). */
            400: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Resource not found. The requested resource is not found. */
            404: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Method not supported. Ensure a proper HTTP method for an HTTP request is used. */
            405: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Not acceptable. The server doesn't support any of the requested by client acceptable content types. */
            406: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Unsupported Media Type. The API is using content negotiation. Ensure the proper media type is set into Content-Type header. */
            415: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Internal Server Error. Something went wrong on the server party. */
            500: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
        };
    };
    getPlaylistItemsRelationship: {
        parameters: {
            query: {
                /**
                 * @description Country code (ISO 3166-1 alpha-2)
                 * @example US
                 */
                countryCode: string;
                /**
                 * @description Allows the client to customize which related resources should be returned. Available options: items
                 * @example items
                 */
                include?: "items"[];
            };
            header?: never;
            path: {
                /**
                 * @description TIDAL playlist id
                 * @example 12345678
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlist items retrieved successfully */
            200: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Playlist_Items_Relationship_Document"];
                };
            };
            /** @description Bad request on client party. Ensure the proper HTTP request is sent (query parameters, request body, etc.). */
            400: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Resource not found. The requested resource is not found. */
            404: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Method not supported. Ensure a proper HTTP method for an HTTP request is used. */
            405: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Not acceptable. The server doesn't support any of the requested by client acceptable content types. */
            406: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Unsupported Media Type. The API is using content negotiation. Ensure the proper media type is set into Content-Type header. */
            415: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Internal Server Error. Something went wrong on the server party. */
            500: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
        };
    };
    getPlaylistCollection: {
        parameters: {
            query?: {
                /**
                 * @description Allows the client to customize which related resources should be returned. Available options: items, owners
                 * @example items
                 */
                include?: ("items" | "owners")[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlists retrieved successfully */
            200: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Playlist_Data_Document"];
                };
            };
            /** @description Bad request on client party. Ensure the proper HTTP request is sent (query parameters, request body, etc.). */
            400: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Resource not found. The requested resource is not found. */
            404: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Method not supported. Ensure a proper HTTP method for an HTTP request is used. */
            405: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Not acceptable. The server doesn't support any of the requested by client acceptable content types. */
            406: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Unsupported Media Type. The API is using content negotiation. Ensure the proper media type is set into Content-Type header. */
            415: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
            /** @description Internal Server Error. Something went wrong on the server party. */
            500: {
                headers: {
                    /**
                     * @description Number of tokens currently remaining. Refer to X-RateLimit-Replenish-Rate header for replenishment information.
                     * @example 5
                     */
                    "X-RateLimit-Remaining": number;
                    /**
                     * @description Initial number of tokens, and max number of tokens that can be replenished.
                     * @example 20
                     */
                    "X-RateLimit-Burst-Capacity": number;
                    /**
                     * @description Number of tokens replenished per second.
                     * @example 5
                     */
                    "X-RateLimit-Replenish-Rate": number;
                    /**
                     * @description Request cost in tokens.
                     * @example 5
                     */
                    "X-RateLimit-Requested-Tokens": number;
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error_Document"];
                };
            };
        };
    };
}
