name: Build module
description: Runs the build for a module
inputs:
  module-path:
    description: The name of the module to build
    required: true
  version:
    description: The semantic version code
    required: true
  tag:
    description: The tag for the release
    required: true
  token:
    description: Github token
    required: true
runs:
  using: composite
  steps:
    - name: Verify Inputs
      id: verify-input
      shell: bash
      env:
        INPUT_MODULE_PATH: ${{ inputs.module-path }}
        INPUT_VERSION: ${{ inputs.version }}
        INPUT_TAG: ${{ inputs.tag }}
      run: |
        output="true"
        echo "Checking if module exists..."
        if [[ ! -d "$INPUT_MODULE_PATH" ]]; then
          output="false"
          echo "Module does not exist!"
        fi

        semver_regex='^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$'

        echo "Checking if version is valid..."

        if [ "$(echo "$INPUT_VERSION" | grep -Eo "$semver_regex")" = "" ]; then
          output="false"
          echo "Invalid version string submitted"
        fi

        echo "Checking if tag is valid"
        name="$INPUT_MODULE_PATH"
        if [ "${name#*/}-$INPUT_VERSION" != "$INPUT_TAG" ]; then
          output="false"
          echo "Invalid tag submitted!"
        fi

        echo "verified=$output" >> $GITHUB_OUTPUT
    - name: Build Module
      shell: bash
      id: build-module
      if: steps.verify-input.outputs.verified == 'true'
      env:
        INPUT_MODULE_PATH: ${{ inputs.module-path }}
        INPUT_VERSION: ${{ inputs.version }}
      run: |
        path="$INPUT_MODULE_PATH"
        name="${path#*/}"
        archive_name="tidal-music-${name}-${INPUT_VERSION}.tgz"

        cd "$path"
        pnpm typecheck
        pnpm pack

        echo "release_file=$path/$archive_name" >> $GITHUB_OUTPUT
    - name: Upload Files To Release Draft
      shell: bash
      env:
        INPUT_TAG: ${{ inputs.tag }}
        RELEASE_FILE: ${{ steps.build-module.outputs.release_file }}
        GH_TOKEN: ${{ inputs.token }}
      run: |
        gh release upload "$INPUT_TAG" "$RELEASE_FILE" --clobber
