name: FOSSA Scans

on:
  workflow_call:

jobs:
    fossa-scan:
        runs-on: ubuntu-latest
        steps:
          - name: "Checkout Code"
            uses: actions/checkout@v6

          - name: "Run FOSSA Scan"
            uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1.9.0
            with:
              api-key: ${{secrets.FOSSAAPIKEY}}
              debug: true

          - name: "FOSSA Tests"
            id: fossa-tests
            uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1.9.0
            with:
              api-key: ${{secrets.FOSSAAPIKEY}}
              run-tests: true
